# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='active',
        ),
        migrations.AddField(
            model_name='click',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
