# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170922_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(default='cool', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
